# Site wide configuration

title: Brandt Lab
description: a family workroom
logo: # 120x120 px default image used for Twitter summary card
teaser: tealbyspa400x250.jpg # 400x250 px default teaser image used in image archive grid
locale: en
url:
shareurl: http://www.brandt.id.au
google_analytics: UA-39801667-1

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist


# Octopress configuration

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: article
page_layout: article

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
  name: Veronica Brandt
  email: veronica@brandt.id.au
  twitter: veromarybrrr
  google:
    ad-client:
    ad-slot:
  bio: Wife and mother, volunteer muso, counsellor and tutor.
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname: brandtlab


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
