name: Brandt Lab
author: Veronica Brandt
title: Brandt Lab
description: A family workroom

url: http://localhost:4000
baseurl: ""
paginate_path: "blog/page:num/"
permalink: date

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: About
   url: /about
 - title: Contact
   url: /contact
 - title: Music
   url: /music
 - title: Education
   url: /education
 - title: Drawings
   url: http://www.peterbrandt.com.au
 - title: Photos
   url: /photos

social:
   github: veromary
   twitter: veromarybrrr
   facebook: veromarybrrr

google_analytics: "UA-39801667-1"
email: veroicon@gmail.com
DISQUS_SITENAME: brandtlab

FEED_RSS: http://feeds.feedburner.com/brandtlab

collections:
  biblestudy:
    output: true
